#!/bin/bash

INFILE="$1"

time java -ea -cp dist/GCParser.jar:extlibs/jargs.jar:extlibs/commons-io-1.4.jar Test.TestGCParserServer -f "$INFILE" -w 80 > results/siserverout &

sleep 0.8

time java -ea -cp dist/GCParser.jar:extlibs/commons-io-1.4.jar:extlibs/jargs.jar Test.TestGCParserClient -f "$INFILE" --server localhost -r 1 > results/siclientout &